### ISSUE TITLE
大佬您好，我在测试您的代码的时候 发现少了一句代码。

### ISSUE THREAD

**Issue by snowyue** [kirbyloco/Pixiv_Downloader#2]
def menu(self):
        print('1.作者UID    3.是否下載R-18圖片 目前=' + self.adult + ' 0=關閉 1=開啟\n2.作品UID')
        mode = str(input('請輸入數字選擇：'))
        if mode == '1':
            spider.getjson(ID)
        elif mode == '2':
            ID = input('請輸入作品ID：')
            spider.medium_manga(ID)
        else:
            self.switchadult()
在149行这里 发现少了一句input(“请输入作者ID”)

**Comment by snowyue** [comment]
有点强迫症，请见谅....

**Comment by kirbyloco** [comment]
Debug時沒發現到，稍後修正
感謝提醒

**Comment by snowyue** [comment]
大佬，我发现一个小问题

**Comment by snowyue** [comment]
如果处理对象为gif，如果是大佬您现有代码的话，不会执行gif()这个函数

**Comment by snowyue** [comment]
在下稍稍改了下，好像没问题 不过执行速度可能稍微慢一点
    def Is_gif(self,ID):
        url = 'https://www.pixiv.net/ajax/illust/' + ID + '/ugoira_meta'
        html = self.session.get(url)
        x = json.loads(html.text)
        if(x['error']=='true'):
            return "true"
        else:
            return "false"
    def medium_manga(self, ID):
        if(self.Is_gif(ID)=="false"):
            
            self.gif(ID)

**Comment by snowyue** [comment]
def Is_gif(self,ID):
        url = 'https://www.pixiv.net/ajax/illust/' + ID + '/ugoira_meta'
        html = self.session.get(url)
        x = json.loads(html.text)
        M_bool=x['error'];
        return M_bool;

    def medium_manga(self, ID):
        if(self.Is_gif(ID)== "false"):
            self.gif(ID)

**Comment by kirbyloco** [comment]
有開啟R-18下載的話，會正常觸發gif()
但由於現在medium_manga()下的判斷過於複雜
這部分之後會在處理

至於判斷gif的方法，大佬的方法不錯
但我希望保留現在採用判斷有無"ugoira"字串
能減少額外的檢查
也減少對pixiv伺服器的壓力

目前預計未來使用單一圖片下載時
不會檢查是否為R-18圖片(畢竟都是親眼確認了

**Comment by snowyue** [comment]
在下的方法可能对用户稍微比较友好，对服务器来说压力可能会有增加

**Comment by kirbyloco** [comment]
稍微想了一下
正常P站在瀏覽時不會一直去請求ugoira_meta來確認是否為GIF
若改用上述方法可能會被P站封鎖(一直回應錯誤
而且畫師大部分都是靜態圖片
很少出現含有大量GIF的情況
就不採用這個方法了

**Comment by snowyue** [comment]
可能我需要重新找找json 才能知道如何处理gif和jpg，png之类的关系

**Comment by kirbyloco** [comment]
略看了Pixiv官方文檔
jpg和png是由畫師上傳的原始檔而定的
動圖是採用多個靜態圖片透過javascript實現類似GIF的功能
也就是在上傳時會Tag為ugoira來區分是否為動圖

**Comment by snowyue** [comment]
那我可能要先取消掉 isgif了，我可能会借用大佬代码 进行二次编程
添加数据库来保存 我要的东西

**Comment by kirbyloco** [comment]
好的，沒有問題

**Comment by snowyue** [comment]
大佬 介意提供一个联系方式吗？

**Comment by kirbyloco** [comment]
沒在用QQ就留微信
ID：kirby2267

**Comment by snowyue** [comment]
大佬，很抱歉最近才有时间上线做自己感兴趣的事情，好像发现 pixiv登录改版了 好像多加了一个参数 虽然我找到了 地方 但是我不会去调用这个js函数来获取recaptcha-v3-token的参数值

**Comment by snowyue** [comment]
在位于login页面的第55行开始：
function grecaptchaCallback() {
            var clientId = grecaptcha.render({
                'sitekey': '6LfJ0Z0UAAAAANqP-8mvUln2z6mHJwuv5YGtC8xp',
            });

            var setRecaptchaV3Token = function() {
                grecaptcha.execute(clientId, {action: 'login'}).then(function(token) {
                    document.getElementById('recaptcha-v3-token').value = token;
                });
            };
多了一个recaptcha-v3-token，的参数 我尝试过一些办法 感觉总是不得要领

**Comment by snowyue** [comment]
对了，如果大佬不嫌弃的话，在下在您的代码的基础上修改出来了第一版的ranking，不过代码只能勉强运行，达不到和主页那样的效果

**Comment by kirbyloco** [comment]
登入的部分我打算改用Pixiv APP的登入接口
網頁的登入就不處理了
